name: CI

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name
  pull_request:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and run custom Qt installer script
        run: |
          # Download the custom installer script (replace URL with your hosted script)
          wget https://example.com/qt-installer.sh
          
          # Make the script executable
          chmod +x qt-installer.sh
          
          # Run the installer script
          ./qt-installer.sh
          
          # Add Qt environment setup as needed

      - name: Build the project
        run: |
          qmake
          make

      - name: Run tests
        run: |
          ./utiltest
