name: CI

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name
  pull_request:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential libgl1-mesa-dev libxkbcommon-x11-0

          # Download and install Qt (Adjust the version and installer link)
          wget https://download.qt.io/official_releases/qt/6.0/6.0.4/qt-6.0.4-linux-x64-online.run
          chmod +x qt-6.0.4-linux-x64-online.run
          sudo ./qt-6.0.4-linux-x64-online.run --silent --platform minimal

      - name: Set up Qt environment
        run: |
          export QTDIR=$HOME/Qt/6.0.4/gcc_64
          export PATH=$QTDIR/bin:$PATH
          export LD_LIBRARY_PATH=$QTDIR/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          export QMAKE=$QTDIR/bin/qmake

      - name: Build the project
        run: |
          qmake
          make

      - name: Run tests
        run: |
          ./utiltest
