name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y qt5-default  # Adjust this for your Qt version

      - name: Build the project
        run: |
          qmake
          make

      - name: Run tests
        run: |
          ./utiltest
